# User initialization file for SciTE4AutoHotkey
#
# You are encouraged to edit this file!
#

# Import the platform-specific settings
import _platform

# Import the settings that can be edited by the bundled properties editor
import _config

AutoHotkeyDir=$(SciteDefaultHome)\AutoHotKey

default.text.size=12

code.page=65001
output.code.page=65001